/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export * as bentoboxv1 from "./bentoboxv1.js";
export {
  BentoBoxV1Processor,
  BentoBoxV1ProcessorTemplate,
} from "./bentoboxv1.js";

export * as masterchefv2 from "./masterchefv2.js";
export {
  MasterChefV2Processor,
  MasterChefV2ProcessorTemplate,
} from "./masterchefv2.js";

export * as sushipair from "./sushipair.js";
export { SushipairProcessor, SushipairProcessorTemplate } from "./sushipair.js";

export * as x2y2 from "./x2y2.js";
export { X2y2Processor, X2y2ProcessorTemplate } from "./x2y2.js";
